export const countries = [
  { value: 'af', label: 'Afghanistan', phoneCode: '+93' },
  { value: 'al', label: 'Albania', phoneCode: '+355' },
  { value: 'dz', label: 'Algeria', phoneCode: '+213' },
  { value: 'as', label: 'American Samoa', phoneCode: '+1-684' },
  { value: 'ad', label: 'Andorra', phoneCode: '+376' },
  { value: 'ao', label: 'Angola', phoneCode: '+244' },
  { value: 'ai', label: 'Anguilla', phoneCode: '+1-264' },
  { value: 'ag', label: 'Antigua and Barbuda', phoneCode: '+1-268' },
  { value: 'ar', label: 'Argentina', phoneCode: '+54' },
  { value: 'am', label: 'Armenia', phoneCode: '+374' },
  { value: 'aw', label: 'Aruba', phoneCode: '+297' },
  { value: 'au', label: 'Australia', phoneCode: '+61' },
  { value: 'at', label: 'Austria', phoneCode: '+43' },
  { value: 'az', label: 'Azerbaijan', phoneCode: '+994' },
  { value: 'bs', label: 'Bahamas', phoneCode: '+1-242' },
  { value: 'bh', label: 'Bahrain', phoneCode: '+973' },
  { value: 'bd', label: 'Bangladesh', phoneCode: '+880' },
  { value: 'bb', label: 'Barbados', phoneCode: '+1-246' },
  { value: 'by', label: 'Belarus', phoneCode: '+375' },
  { value: 'be', label: 'Belgium', phoneCode: '+32' },
  { value: 'bz', label: 'Belize', phoneCode: '+501' },
  { value: 'bj', label: 'Benin', phoneCode: '+229' },
  { value: 'bm', label: 'Bermuda', phoneCode: '+1-441' },
  { value: 'bt', label: 'Bhutan', phoneCode: '+975' },
  { value: 'bo', label: 'Bolivia', phoneCode: '+591' },
  { value: 'ba', label: 'Bosnia and Herzegovina', phoneCode: '+387' },
  { value: 'bw', label: 'Botswana', phoneCode: '+267' },
  { value: 'br', label: 'Brazil', phoneCode: '+55' },
  { value: 'bn', label: 'Brunei', phoneCode: '+673' },
  { value: 'bg', label: 'Bulgaria', phoneCode: '+359' },
  { value: 'bf', label: 'Burkina Faso', phoneCode: '+226' },
  { value: 'bi', label: 'Burundi', phoneCode: '+257' },
  { value: 'kh', label: 'Cambodia', phoneCode: '+855' },
  { value: 'cm', label: 'Cameroon', phoneCode: '+237' },
  { value: 'ca', label: 'Canada', phoneCode: '+1' },
  { value: 'cv', label: 'Cape Verde', phoneCode: '+238' },
  { value: 'ky', label: 'Cayman Islands', phoneCode: '+1-345' },
  { value: 'cf', label: 'Central African Republic', phoneCode: '+236' },
  { value: 'td', label: 'Chad', phoneCode: '+235' },
  { value: 'cl', label: 'Chile', phoneCode: '+56' },
  { value: 'cn', label: 'China', phoneCode: '+86' },
  { value: 'co', label: 'Colombia', phoneCode: '+57' },
  { value: 'km', label: 'Comoros', phoneCode: '+269' },
  { value: 'cg', label: 'Congo', phoneCode: '+242' },
  { value: 'cd', label: 'Congo, Democratic Republic', phoneCode: '+243' },
  { value: 'ck', label: 'Cook Islands', phoneCode: '+682' },
  { value: 'cr', label: 'Costa Rica', phoneCode: '+506' },
  { value: 'hr', label: 'Croatia', phoneCode: '+385' },
  { value: 'cu', label: 'Cuba', phoneCode: '+53' },
  { value: 'cy', label: 'Cyprus', phoneCode: '+357' },
  { value: 'cz', label: 'Czech Republic', phoneCode: '+420' },
  { value: 'dk', label: 'Denmark', phoneCode: '+45' },
  { value: 'dj', label: 'Djibouti', phoneCode: '+253' },
  { value: 'dm', label: 'Dominica', phoneCode: '+1-767' },
  { value: 'do', label: 'Dominican Republic', phoneCode: '+1-809' },
  { value: 'ec', label: 'Ecuador', phoneCode: '+593' },
  { value: 'eg', label: 'Egypt', phoneCode: '+20' },
  { value: 'sv', label: 'El Salvador', phoneCode: '+503' },
  { value: 'gq', label: 'Equatorial Guinea', phoneCode: '+240' },
  { value: 'er', label: 'Eritrea', phoneCode: '+291' },
  { value: 'ee', label: 'Estonia', phoneCode: '+372' },
  { value: 'et', label: 'Ethiopia', phoneCode: '+251' },
  { value: 'fk', label: 'Falkland Islands', phoneCode: '+500' },
  { value: 'fo', label: 'Faroe Islands', phoneCode: '+298' },
  { value: 'fj', label: 'Fiji', phoneCode: '+679' },
  { value: 'fi', label: 'Finland', phoneCode: '+358' },
  { value: 'fr', label: 'France', phoneCode: '+33' },
  { value: 'pf', label: 'French Polynesia', phoneCode: '+689' },
  { value: 'ga', label: 'Gabon', phoneCode: '+241' },
  { value: 'gm', label: 'Gambia', phoneCode: '+220' },
  { value: 'ge', label: 'Georgia', phoneCode: '+995' },
  { value: 'de', label: 'Germany', phoneCode: '+49' },
  { value: 'gh', label: 'Ghana', phoneCode: '+233' },
  { value: 'gi', label: 'Gibraltar', phoneCode: '+350' },
  { value: 'gr', label: 'Greece', phoneCode: '+30' },
  { value: 'gl', label: 'Greenland', phoneCode: '+299' },
  { value: 'gd', label: 'Grenada', phoneCode: '+1-473' },
  { value: 'gu', label: 'Guam', phoneCode: '+1-671' },
  { value: 'gt', label: 'Guatemala', phoneCode: '+502' },
  { value: 'gn', label: 'Guinea', phoneCode: '+224' },
  { value: 'gw', label: 'Guinea-Bissau', phoneCode: '+245' },
  { value: 'gy', label: 'Guyana', phoneCode: '+592' },
  { value: 'ht', label: 'Haiti', phoneCode: '+509' },
  { value: 'hn', label: 'Honduras', phoneCode: '+504' },
  { value: 'hk', label: 'Hong Kong', phoneCode: '+852' },
  { value: 'hu', label: 'Hungary', phoneCode: '+36' },
  { value: 'is', label: 'Iceland', phoneCode: '+354' },
  { value: 'in', label: 'India', phoneCode: '+91' },
  { value: 'id', label: 'Indonesia', phoneCode: '+62' },
  { value: 'ir', label: 'Iran', phoneCode: '+98' },
  { value: 'iq', label: 'Iraq', phoneCode: '+964' },
  { value: 'ie', label: 'Ireland', phoneCode: '+353' },
  { value: 'il', label: 'Israel', phoneCode: '+972' },
  { value: 'it', label: 'Italy', phoneCode: '+39' },
  { value: 'jm', label: 'Jamaica', phoneCode: '+1-876' },
  { value: 'jp', label: 'Japan', phoneCode: '+81' },
  { value: 'jo', label: 'Jordan', phoneCode: '+962' },
  { value: 'kz', label: 'Kazakhstan', phoneCode: '+7' },
  { value: 'ke', label: 'Kenya', phoneCode: '+254' },
  { value: 'ki', label: 'Kiribati', phoneCode: '+686' },
  { value: 'kr', label: 'Korea, South', phoneCode: '+82' },
  { value: 'kw', label: 'Kuwait', phoneCode: '+965' },
  { value: 'kg', label: 'Kyrgyzstan', phoneCode: '+996' },
  { value: 'la', label: 'Laos', phoneCode: '+856' },
  { value: 'lv', label: 'Latvia', phoneCode: '+371' },
  { value: 'lb', label: 'Lebanon', phoneCode: '+961' },
  { value: 'ls', label: 'Lesotho', phoneCode: '+266' },
  { value: 'lr', label: 'Liberia', phoneCode: '+231' },
  { value: 'ly', label: 'Libya', phoneCode: '+218' },
  { value: 'li', label: 'Liechtenstein', phoneCode: '+423' },
  { value: 'lt', label: 'Lithuania', phoneCode: '+370' },
  { value: 'lu', label: 'Luxembourg', phoneCode: '+352' },
  { value: 'mo', label: 'Macao', phoneCode: '+853' },
  { value: 'mk', label: 'Macedonia', phoneCode: '+389' },
  { value: 'mg', label: 'Madagascar', phoneCode: '+261' },
  { value: 'mw', label: 'Malawi', phoneCode: '+265' },
  { value: 'my', label: 'Malaysia', phoneCode: '+60' },
  { value: 'mv', label: 'Maldives', phoneCode: '+960' },
  { value: 'ml', label: 'Mali', phoneCode: '+223' },
  { value: 'mt', label: 'Malta', phoneCode: '+356' },
  { value: 'mh', label: 'Marshall Islands', phoneCode: '+692' },
  { value: 'mr', label: 'Mauritania', phoneCode: '+222' },
  { value: 'mu', label: 'Mauritius', phoneCode: '+230' },
  { value: 'mx', label: 'Mexico', phoneCode: '+52' },
  { value: 'fm', label: 'Micronesia', phoneCode: '+691' },
  { value: 'md', label: 'Moldova', phoneCode: '+373' },
  { value: 'mc', label: 'Monaco', phoneCode: '+377' },
  { value: 'mn', label: 'Mongolia', phoneCode: '+976' },
  { value: 'me', label: 'Montenegro', phoneCode: '+382' },
  { value: 'ms', label: 'Montserrat', phoneCode: '+1-664' },
  { value: 'ma', label: 'Morocco', phoneCode: '+212' },
  { value: 'mz', label: 'Mozambique', phoneCode: '+258' },
  { value: 'mm', label: 'Myanmar', phoneCode: '+95' },
  { value: 'na', label: 'Namibia', phoneCode: '+264' },
  { value: 'nr', label: 'Nauru', phoneCode: '+674' },
  { value: 'np', label: 'Nepal', phoneCode: '+977' },
  { value: 'nl', label: 'Netherlands', phoneCode: '+31' },
  { value: 'nc', label: 'New Caledonia', phoneCode: '+687' },
  { value: 'nz', label: 'New Zealand', phoneCode: '+64' },
  { value: 'ni', label: 'Nicaragua', phoneCode: '+505' },
  { value: 'ne', label: 'Niger', phoneCode: '+227' },
  { value: 'ng', label: 'Nigeria', phoneCode: '+234' },
  { value: 'nu', label: 'Niue', phoneCode: '+683' },
  { value: 'nf', label: 'Norfolk Island', phoneCode: '+672' },
  { value: 'mp', label: 'Northern Mariana Islands', phoneCode: '+1-670' },
  { value: 'no', label: 'Norway', phoneCode: '+47' },
  { value: 'om', label: 'Oman', phoneCode: '+968' },
  { value: 'pk', label: 'Pakistan', phoneCode: '+92' },
  { value: 'pw', label: 'Palau', phoneCode: '+680' },
  { value: 'ps', label: 'Palestine', phoneCode: '+970' },
  { value: 'pa', label: 'Panama', phoneCode: '+507' },
  { value: 'pg', label: 'Papua New Guinea', phoneCode: '+675' },
  { value: 'py', label: 'Paraguay', phoneCode: '+595' },
  { value: 'pe', label: 'Peru', phoneCode: '+51' },
  { value: 'ph', label: 'Philippines', phoneCode: '+63' },
  { value: 'pl', label: 'Poland', phoneCode: '+48' },
  { value: 'pt', label: 'Portugal', phoneCode: '+351' },
  { value: 'pr', label: 'Puerto Rico', phoneCode: '+1-787' },
  { value: 'qa', label: 'Qatar', phoneCode: '+974' },
  { value: 're', label: 'Reunion', phoneCode: '+262' },
  { value: 'ro', label: 'Romania', phoneCode: '+40' },
  { value: 'ru', label: 'Russia', phoneCode: '+7' },
  { value: 'rw', label: 'Rwanda', phoneCode: '+250' },
  { value: 'kn', label: 'Saint Kitts and Nevis', phoneCode: '+1-869' },
  { value: 'lc', label: 'Saint Lucia', phoneCode: '+1-758' },
  { value: 'vc', label: 'Saint Vincent', phoneCode: '+1-784' },
  { value: 'ws', label: 'Samoa', phoneCode: '+685' },
  { value: 'sm', label: 'San Marino', phoneCode: '+378' },
  { value: 'st', label: 'Sao Tome and Principe', phoneCode: '+239' },
  { value: 'sa', label: 'Saudi Arabia', phoneCode: '+966' },
  { value: 'sn', label: 'Senegal', phoneCode: '+221' },
  { value: 'rs', label: 'Serbia', phoneCode: '+381' },
  { value: 'sc', label: 'Seychelles', phoneCode: '+248' },
  { value: 'sl', label: 'Sierra Leone', phoneCode: '+232' },
  { value: 'sg', label: 'Singapore', phoneCode: '+65' },
  { value: 'sk', label: 'Slovakia', phoneCode: '+421' },
  { value: 'si', label: 'Slovenia', phoneCode: '+386' },
  { value: 'sb', label: 'Solomon Islands', phoneCode: '+677' },
  { value: 'so', label: 'Somalia', phoneCode: '+252' },
  { value: 'za', label: 'South Africa', phoneCode: '+27' },
  { value: 'ss', label: 'South Sudan', phoneCode: '+211' },
  { value: 'es', label: 'Spain', phoneCode: '+34' },
  { value: 'lk', label: 'Sri Lanka', phoneCode: '+94' },
  { value: 'sd', label: 'Sudan', phoneCode: '+249' },
  { value: 'sr', label: 'Suriname', phoneCode: '+597' },
  { value: 'sz', label: 'Swaziland', phoneCode: '+268' },
  { value: 'se', label: 'Sweden', phoneCode: '+46' },
  { value: 'ch', label: 'Switzerland', phoneCode: '+41' },
  { value: 'sy', label: 'Syria', phoneCode: '+963' },
  { value: 'tw', label: 'Taiwan', phoneCode: '+886' },
  { value: 'tj', label: 'Tajikistan', phoneCode: '+992' },
  { value: 'tz', label: 'Tanzania', phoneCode: '+255' },
  { value: 'th', label: 'Thailand', phoneCode: '+66' },
  { value: 'tl', label: 'Timor-Leste', phoneCode: '+670' },
  { value: 'tg', label: 'Togo', phoneCode: '+228' },
  { value: 'tk', label: 'Tokelau', phoneCode: '+690' },
  { value: 'to', label: 'Tonga', phoneCode: '+676' },
  { value: 'tt', label: 'Trinidad and Tobago', phoneCode: '+1-868' },
  { value: 'tn', label: 'Tunisia', phoneCode: '+216' },
  { value: 'tr', label: 'Turkey', phoneCode: '+90' },
  { value: 'tm', label: 'Turkmenistan', phoneCode: '+993' },
  { value: 'tc', label: 'Turks and Caicos Islands', phoneCode: '+1-649' },
  { value: 'tv', label: 'Tuvalu', phoneCode: '+688' },
  { value: 'ug', label: 'Uganda', phoneCode: '+256' },
  { value: 'ua', label: 'Ukraine', phoneCode: '+380' },
  { value: 'ae', label: 'United Arab Emirates', phoneCode: '+971' },
  { value: 'gb', label: 'United Kingdom', phoneCode: '+44' },
  { value: 'us', label: 'United States', phoneCode: '+1' },
  { value: 'uy', label: 'Uruguay', phoneCode: '+598' },
  { value: 'uz', label: 'Uzbekistan', phoneCode: '+998' },
  { value: 'vu', label: 'Vanuatu', phoneCode: '+678' },
  { value: 'va', label: 'Vatican City', phoneCode: '+379' },
  { value: 've', label: 'Venezuela', phoneCode: '+58' },
  { value: 'vn', label: 'Vietnam', phoneCode: '+84' },
  { value: 'vg', label: 'Virgin Islands, British', phoneCode: '+1-284' },
  { value: 'vi', label: 'Virgin Islands, US', phoneCode: '+1-340' },
  { value: 'wf', label: 'Wallis and Futuna', phoneCode: '+681' },
  { value: 'ye', label: 'Yemen', phoneCode: '+967' },
  { value: 'zm', label: 'Zambia', phoneCode: '+260' },
  { value: 'zw', label: 'Zimbabwe', phoneCode: '+263' },
]
